### PR TITLE
Print timer of `SummaryCallback` in `finalize`r

### PR DESCRIPTION
**Pull request by JoshuaLampert**
This way the timer of the summary callback is printed at the end of the simulation and not at the end of the last timestep.

### CODE REVIEW

**Review by ranocha — DISMISSED** [review]
Thanks!

**Review by ranocha — DISMISSED** [review]

**Comment by JoshuaLampert** [comment]
Newer versions of OrdinaryDiffEq.jl (including v6.59.3, which is needed for the `finalize` function to work) require Julia v1.9. Thus, the tests use Julia v1.9, now.

**Comment by ranocha** [comment]
If you update the IC tests to Julia v1.9, you should also update the Julia requirement in https://github.com/JoshuaLampert/DispersiveShallowWater.jl/blob/492f918f040f3103f9b062d21538d36e9a2c877a/Project.toml#L37

**Comment by JoshuaLampert** [comment]
Done in [1107493](https://github.com/JoshuaLampert/DispersiveShallowWater.jl/pull/79/commits/11074931d1fa431f4faf8e0f886480c505640eb1)

**Comment by ranocha** [comment]
> > If you update the IC tests to Julia v1.9, you should also update the Julia requirement
> 
> This is not the case for Trixi.jl. Should this be adapted there, too?

No, we explicitly keep some tests with Julia v1.8 in the Trixi.jl repo 

https://github.com/trixi-framework/Trixi.jl/blob/b5d0a50214abb9b33dc4a4859a4a12c6e3149cb1/.github/workflows/ci.yml#L83-L86

**Comment by JoshuaLampert** [comment]
Ah ok, thanks!

**Comment by JoshuaLampert** [comment]
> Sorry, I was too fast. There are other references to v1.8 of Julia, e.g.

Done in [b3ea701](https://github.com/JoshuaLampert/DispersiveShallowWater.jl/pull/79/commits/b3ea701b883e05744f01794c982b38a28861dde9).

**Review by ranocha — APPROVED** [review]
Thanks!

**Pull request merged**
